package lmiguelmh.test.ui;

import lmiguelmh.test.examples.App2;
import org.apache.jena.rdf.model.InfModel;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.reasoner.Reasoner;
import org.apache.jena.reasoner.ReasonerRegistry;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.io.InputStream;

import static lmiguelmh.test.examples.App2.query;
import static lmiguelmh.test.examples.App2.readModelFromFactory;

public class SparqlUI extends JDialog {
  private JPanel contentPane;
  private JButton buttonOK;
  private JButton buttonCancel;
  private JTextField owlFileTxt;
  private JButton owlLoadBtn;
  private JTextArea queryTxt;
  private JTextArea resultTxt;
  private JButton queryBtn;

  private Model model;

  public SparqlUI() {
    setContentPane(contentPane);
    setModal(true);
    getRootPane().setDefaultButton(buttonOK);

    buttonOK.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onOK();
      }
    });

    buttonCancel.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onCancel();
      }
    });

// call onCancel() when cross is clicked
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        onCancel();
      }
    });

// call onCancel() on ESCAPE
    contentPane.registerKeyboardAction(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onCancel();
      }
    }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    owlLoadBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        try {
          InputStream slangIs = App2.class.getClassLoader().getResourceAsStream(owlFileTxt.getText());
          model = readModelFromFactory(slangIs);
          showInfo("OWL file loaded!");

        } catch (Exception e1) {
          e1.printStackTrace();
          showError(e1.getMessage());
        }
      }
    });
    queryBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        if (model == null) {
          showError("Load the OWL file first!");
          return;
        }

        try {
          Reasoner owlReasoner = ReasonerRegistry.getOWLReasoner();
          Reasoner wnReasoner = owlReasoner.bindSchema(model);
          InfModel infModel = ModelFactory.createInfModel(wnReasoner, model);
          String queryString = queryTxt.getText();
          String result = query(infModel, queryString, "txt");
          resultTxt.setText(result);

        } catch (Exception e1) {
          e1.printStackTrace();
          showError(e1.getMessage());
        }
      }
    });
  }

  private void showInfo(String message) {
    JOptionPane.showOptionDialog(this, message, "Info", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
  }

  private void showError(String message) {
    JOptionPane.showOptionDialog(this, message, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
  }

  private void onOK() {
// add your code here
    dispose();
  }

  private void onCancel() {
// add your code here if necessary
    dispose();
  }

  public static void main(String[] args) {
    SparqlUI dialog = new SparqlUI();
    dialog.pack();
    dialog.setVisible(true);
    System.exit(0);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPane = new JPanel();
    contentPane.setLayout(new BorderLayout(0, 0));
    contentPane.setMinimumSize(new Dimension(640, 480));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    contentPane.add(panel1, BorderLayout.CENTER);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel1.add(panel2, BorderLayout.NORTH);
    final JLabel label1 = new JLabel();
    label1.setText("Query string");
    panel2.add(label1);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel2.add(panel3);
    final JScrollPane scrollPane1 = new JScrollPane();
    panel3.add(scrollPane1);
    queryTxt = new JTextArea();
    queryTxt.setColumns(50);
    queryTxt.setFont(new Font("Consolas", queryTxt.getFont().getStyle(), queryTxt.getFont().getSize()));
    queryTxt.setRows(6);
    queryTxt.setText(" SELECT \n ?v \n WHERE \n {\n ?slang <http://lmiguelmh/slang#meaning> \"piña\" .\n ?word <http://lmiguelmh/slang#hasSlang> ?slang .\n ?word <http://lmiguelmh/slang#hasSlang> ?s .\n ?s <http://lmiguelmh/slang#value> ?v .\n } ");
    scrollPane1.setViewportView(queryTxt);
    queryBtn = new JButton();
    queryBtn.setText("Query");
    panel2.add(queryBtn);
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new BorderLayout(0, 0));
    panel1.add(panel4, BorderLayout.CENTER);
    panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
    final JScrollPane scrollPane2 = new JScrollPane();
    panel4.add(scrollPane2, BorderLayout.CENTER);
    resultTxt = new JTextArea();
    resultTxt.setFont(new Font("Consolas", resultTxt.getFont().getStyle(), resultTxt.getFont().getSize()));
    resultTxt.setRows(10);
    scrollPane2.setViewportView(resultTxt);
    final JPanel panel5 = new JPanel();
    panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    contentPane.add(panel5, BorderLayout.SOUTH);
    buttonOK = new JButton();
    buttonOK.setText("OK");
    panel5.add(buttonOK);
    buttonCancel = new JButton();
    buttonCancel.setText("Cancel");
    panel5.add(buttonCancel);
    final JPanel panel6 = new JPanel();
    panel6.setLayout(new BorderLayout(0, 0));
    contentPane.add(panel6, BorderLayout.NORTH);
    final JPanel panel7 = new JPanel();
    panel7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel6.add(panel7, BorderLayout.SOUTH);
    final JLabel label2 = new JLabel();
    label2.setText("OWL file");
    panel7.add(label2);
    owlFileTxt = new JTextField();
    owlFileTxt.setColumns(24);
    owlFileTxt.setFont(new Font("Consolas", owlFileTxt.getFont().getStyle(), owlFileTxt.getFont().getSize()));
    owlFileTxt.setText("slang.owl");
    panel7.add(owlFileTxt);
    owlLoadBtn = new JButton();
    owlLoadBtn.setText("Load");
    panel7.add(owlLoadBtn);
    final JPanel panel8 = new JPanel();
    panel8.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel6.add(panel8, BorderLayout.CENTER);
    final JLabel label3 = new JLabel();
    label3.setText("SPARQL UI");
    panel8.add(label3);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPane;
  }
}
